package com.example.hospitalstocks.Services;

import com.example.hospitalstocks.Entities.Entry;
import com.example.hospitalstocks.Entities.Stock;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

@Service
public class PDFService {

    public String generateEntryPDF(Entry entry) {
        String pdfPath = "entry_" + entry.getId() + ".pdf";
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(pdfPath));
            document.open();

            // Adding title with styling
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.BLACK);
            Paragraph title = new Paragraph("Entry Details", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Adding table with entry details
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Table header
            PdfPCell header1 = new PdfPCell(new Phrase("Field"));
            PdfPCell header2 = new PdfPCell(new Phrase("Value"));
            header1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            header2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            table.addCell(header1);
            table.addCell(header2);

            // Adding entry details to the table
            addTableRow(table, "Entry ID", entry.getId().toString());
            addTableRow(table, "Date", entry.getDate().toString());
            addTableRow(table, "Quantity", entry.getQuantity().toString());
            addTableRow(table, "Drug", entry.getDrug().getName());

            document.add(table);

            // Adding footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
            Paragraph footer = new Paragraph("Generated by Hospital Stock Management System", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(30);
            document.add(footer);

        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        } finally {
            document.close();
        }

        return pdfPath;
    }

    private void addTableRow(PdfPTable table, String fieldName, String fieldValue) {
        table.addCell(new Phrase(fieldName));
        table.addCell(new Phrase(fieldValue));
    }

    public String generateStockPDF(Stock stock) {
        String pdfPath = "stock_" + stock.getId() + ".pdf";
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(pdfPath));
            document.open();

            // Adding title with styling
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.BLACK);
            Paragraph title = new Paragraph("Stock Details", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Adding table with stock details
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Table header
            PdfPCell header1 = new PdfPCell(new Phrase("Field"));
            PdfPCell header2 = new PdfPCell(new Phrase("Value"));
            header1.setBackgroundColor(BaseColor.LIGHT_GRAY);
            header2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            table.addCell(header1);
            table.addCell(header2);

            // Adding stock details to the table
            addTableRow(table, "Stock ID", stock.getId().toString());
            addTableRow(table, "Date", stock.getExpiryDate().toString());
            addTableRow(table, "Quantity", String.valueOf(stock.getQuantity()));
            addTableRow(table, "Drug", stock.getDrug().getName());

            document.add(table);

            // Adding footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
            Paragraph footer = new Paragraph("Generated by Hospital Stock Management System", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(30);
            document.add(footer);

        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        } finally {
            document.close();
        }

        return pdfPath;
    }
}
